apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secret.fullname | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
  mariadb-password: ZWNvbXBhc3N3b3JkCg==
  mariadb-root-password: ZWNvbXBhc3N3b3JkCg==