apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.storage.claimName | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: {{ .Values.database.storage.size | quote }}