apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.service.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    {{- toYaml .Values.database.labels | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}
  type: {{ .Values.database.service.type | quote }}