apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.website.service.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ .Values.website.service.type | quote }}
  selector:
    {{- toYaml .Values.website.labels | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.website.service.port }}